Add integration tests
osu-mist/old-students-api pull request #10
Opened 2018-11-02 22:42 UTC by jaredkosanovic

- Adds integration tests. The integration tests interact with swagger.yaml to compare the API spec to the actual response.
- Minor corrections to swagger.yaml
- Logic change for the class schedule resource.

2018-11-05 17:56 UTC, tsoliangwu0130 requested changes

2018-11-05 17:56 UTC, tsoliangwu0130 commented on src/test/integration/integration_tests.py
> +        cls.auth_header = {'Authorization': 'Bearer {}'.format(access_token)}
Could you use f-string to format the header as you did elsewhere for the consistency?

2018-11-05 17:56 UTC, tsoliangwu0130 commented on src/test/integration/integration_tests.py
> +        request = requests.get(url, params=params, headers=self.auth_header)
Not a big deal, but I think we should name the variable to be `res` or `response` to represent the "response" you get from the `request.get` call. Naming it as `request` is a bit misleading to me.

2018-11-05 17:56 UTC, tsoliangwu0130 commented on src/test/integration/integration_tests.py
> +        logging.debug("Request took {} second(s)".format(elapsed_seconds))
Could you use f-string here as well?

2018-11-05 17:56 UTC, tsoliangwu0130 commented on src/test/integration/integration_tests.py
> +        self.assertEqual(len(errors), 1)
Will this be always one error in the errors object? I'm thinking maybe at least we shouldn't assert the errors object will only include one error for the most of `400` errors since we might implement more parameters in the future, and it may return multiple `400`‘s in a errors object. What do you think?

2018-11-05 17:56 UTC, tsoliangwu0130 commented on src/test/integration/integration_tests.py
> +                format = field_properties["format"]
`format` is one of the Python reserved keywords. You could either [add a trailing underscore](https://stackoverflow.com/questions/21075208/whats-the-advantage-of-a-trailing-underscore-in-python-naming) to it or name it differently to avoid any potential conflict.

2018-11-05 17:56 UTC, tsoliangwu0130 commented on src/test/integration/integration_tests.py
> +                    self.assert_date_format(actual[field], "%Y-%m-%d")
Just my two cents, instead of using multiple if-else statements, what do you think about using a dictionary to store all available format types and their formats? I think it will be easier to extend if we have more types in the future, and also helps the readability a bit.

2018-11-05 17:56 UTC, tsoliangwu0130 commented on src/test/integration/integration_tests.py
> +            if plain_type == "string":
Same with my above comments, I guess we can avoid too many if-else statements by having a translation dictionary.

2018-11-05 17:56 UTC, tsoliangwu0130 commented on src/test/integration/integration_tests.py
> +                properties["transactions"]["items"]["properties"], transaction)
Since the logic of most of these testing against various endpoints are pretty much the same, do you think we can combine them together or having another function to share the testing logic if you wanna separate the test cases by endpoints?

2018-11-05 17:56 UTC, tsoliangwu0130 commented on src/test/integration/requirements.txt
> +requests>=2.18.4
We should use requests to version 2.20.0 or later due to a potential security vulnerability issue.

![screen shot 2018-11-05 at 9 53 54 am](https://user-images.githubusercontent.com/9169491/48016638-f6a36680-e0e0-11e8-9872-86e1873f71be.png)

2018-11-05 20:22 UTC, jaredkosanovic commented on src/test/integration/integration_tests.py
> +        self.assertEqual(len(errors), 1)
Right now, every endpoint of this API would return a maximum of 1 error in a given error response. It's not too trivial to update this method to check multiple error messages, so I'm going to keep it how it is for now until we have a use case where we need to check multiple errors.

2018-11-05 21:11 UTC, jaredkosanovic commented on src/test/integration/integration_tests.py
> +                properties["transactions"]["items"]["properties"], transaction)
I was considering that but I kept them all mostly separate because each one is slightly different. Some test arrays of objects, and some don't. Some resource objects contains an array in the attributes object, and some don't.

I think a good long term solution would be to have our skeleton integration tests simply read off the the open api spec and test everything automatically. That way, we would need to write minimal code for new integration tests, and all integration tests code would look pretty much the same since it would just be checking again the openapi spec.

2018-11-05 21:11 UTC, jaredkosanovic commented on src/test/integration/requirements.txt
> +requests>=2.18.4
Good catch.

2018-11-05 21:14 UTC, jaredkosanovic commented on src/test/integration/integration_tests.py
> +            if plain_type == "string":
Do you have any suggestions for this? I started to take a look at it and I wasn't sure how to implement a translation dict for the complex "number" type.

2018-11-05 22:25 UTC, tsoliangwu0130 commented on src/test/integration/integration_tests.py
> +            if plain_type == "string":
Could do something like that:

```suggestion
            type_dict = {
                'string': str,
                'number': int,
                'integer': int,
                'int32': int,
                'int64':int,
                'float': float,
                'double': float,
                'boolean': bool,
                'array': list,
                'object': dict
            }

            type_key = properties['format'] if 'format' in properties else plain_type
            return type_dict[type_key]
```

I didn't check if there is any pep8/flake8 warning, just an idea or something like that.

2018-11-06 00:11 UTC, jaredkosanovic commented on src/test/integration/Dockerfile
> +COPY swagger.yaml .
I had to change the context of this dockerfile in order to copy the swagger.yaml file. See my commit message for more details: https://github.com/osu-mist/students-api/pull/10/commits/2bc33facf746f9d2975e16de3b99282de80d5e23

2018-11-06 00:44 UTC, tsoliangwu0130 approved these changes

2018-11-06 00:44 UTC, tsoliangwu0130 commented on src/test/integration/integration_tests.py
> +                "format"] if "format" in properties else properties["type"]
Feel free to ignore. The newline breaks in a weird position.

2018-11-06 14:56 UTC, jaredkosanovic commented on src/test/integration/integration_tests.py
> +                "format"] if "format" in properties else properties["type"]
I agree. Suggestions? I couldn't fine a good way to break up that line.

2018-11-06 16:45 UTC, tsoliangwu0130 commented on src/test/integration/integration_tests.py
> +                "format"] if "format" in properties else properties["type"]
I think you could use `\` for [line continuation](https://www.python.org/dev/peps/pep-0008/#maximum-line-length) like this:

```python
plain_type = properties["format"] \
    if "format" in properties \
    else properties["type"]
```

or you can name the variables shortly, either way.

2018-11-06 19:45 UTC, merged