Refactor Students API
osu-mist/old-students-api pull request #6
Opened 2018-09-19 22:03 UTC by jaredkosanovic

This API was the product of a few hackathon, so this PR is meant to refactor the API to allow it to be ready for a stable release.

2018-09-25 16:49 UTC, tsoliangwu0130 requested changes

2018-09-25 16:49 UTC, tsoliangwu0130 commented on swagger.yaml
>  basePath: /v1/students
`basePath` should only include`/v1`, and `/students` should go to the `path` object: https://swagger.io/docs/specification/2-0/api-host-and-base-path/

2018-09-25 16:49 UTC, tsoliangwu0130 commented on swagger.yaml
> +                      example: "P"
What does 'P' stands for? Can we return a more descriptive data like getting descriptions from the validation tables instead of just an indicator? In addition, can we also add an `enum` field to list all possible values?

2018-09-25 16:49 UTC, tsoliangwu0130 commented on swagger.yaml
> +            example: "931234567"
Some of these ID objects (same as term object) is redefined multiple times among ResultObjects, could you move them to `definitions` and make them reusable? By doing this, we could probably also give these ID objects more descriptive name like `StudentOsuIdObject` or `AcademicStatusIdObject` something like that.

2018-09-25 16:49 UTC, tsoliangwu0130 commented on swagger.yaml
> +                  example: "Honor Roll"
How many different possible values can `deansList` be? Is it possible to have `enum` for this field as well?

2018-09-25 16:49 UTC, tsoliangwu0130 commented on swagger.yaml
> +        example: "578.70"
I'm not sure, but should we treat `gpa` and `qualityPoints` as numbers as well?

2018-09-27 17:17 UTC, jaredkosanovic commented on swagger.yaml
> +                      example: "P"
I'm honestly not sure. The only transaction type I can see is "P". Maybe it means payment? I will remove that field since there's not much information or need for it.

2018-09-27 17:29 UTC, jaredkosanovic commented on swagger.yaml
> +            example: "931234567"
Good idea.

2018-09-27 17:38 UTC, jaredkosanovic commented on swagger.yaml
> +                  example: "Honor Roll"
I think this will only ever be `null` or "Honor Roll". I will remove this field since it doesn't add much value.

2018-09-27 17:40 UTC, jaredkosanovic commented on swagger.yaml
> +        example: "578.70"
Ellucian's API treats those fields as strings, so I didn't want to change that. I'm not sure if those fields could ever return non-numbers.

2018-10-05 22:39 UTC, tsoliangwu0130 requested changes

2018-10-05 22:39 UTC, tsoliangwu0130 commented on swagger.yaml
> +            example: "account-transactions"
Since there is a `links` property defined in [ResourceObject](https://github.com/osu-mist/students-api/blob/feature/CO-1203-students-api/src/main/groovy/edu/oregonstate/mist/api/jsonapi/ResourceObject.groovy#L7) but we didn't define and return any link in either swagger or implementation level, we'll always get `links: null` for every resource object. For instance:

```json
{
    "links": {
        "self": "https://api.oregonstate.edu/v1/students/930582979/academic-status?term=201203"
    },
    "data": [
        {
            "id": "930582979-201203",
            "type": "academic-status",
            "attributes": {
                someAttributes: ...
            },
            "links": null
        }
    ]
}
```

This seems odd. According to [JSON API specification](http://jsonapi.org/format/#document-resource-objects), links object in resource object is not required, maybe we should make it optional in our skeleton?

2018-10-09 21:12 UTC, tsoliangwu0130 approved these changes
Fair, looks good.

2018-10-10 13:48 UTC, merged