CO-1219 add academic level
osu-mist/old-students-api pull request #9
Opened 2018-10-25 21:22 UTC by tsoliangwu0130

2018-10-26 15:26 UTC, jaredkosanovic requested changes

2018-10-26 15:26 UTC, jaredkosanovic commented on swagger.yaml
> +                  - "Obsolete - Do not use"
I'm thinking we should remove this since it says to not use.

2018-10-26 15:26 UTC, jaredkosanovic commented on swagger.yaml
> +              firstName:
We already have names in the persons API. Does it make sense to duplicate it here?

2018-10-26 15:26 UTC, jaredkosanovic commented on src/main/groovy/edu/oregonstate/mist/students/db/HttpStudentsDAO.groovy
> +import groovy.json.JsonSlurper
Can we continue using Jackson in this class instead? I don't think it makes sense having two different json deserializer libraries.

2018-10-26 15:26 UTC, jaredkosanovic commented on src/main/groovy/edu/oregonstate/mist/students/db/HttpStudentsDAO.groovy
> +    protected Map getPerson(String bannerId) {
Can we just use a generic `id` instead of `bannerId`? Or we can change all the id's to be `personID` or something... Just as long as it's consistent.

2018-10-26 15:26 UTC, jaredkosanovic commented on src/main/groovy/edu/oregonstate/mist/students/db/HttpStudentsDAO.groovy
> +            getStudentsEndpoint(id, classSchedulesEndpoint), ["term": term]
`["term": term]` is repeated a few times. What do you think about creating a `getTermParameterMap` method or something?

2018-10-26 15:26 UTC, jaredkosanovic commented on src/main/groovy/edu/oregonstate/mist/students/db/HttpStudentsDAO.groovy
> +            // API will return with a malformed academic standing object. The best way I"ve found to
Why the edits in this comment?

2018-10-26 15:26 UTC, jaredkosanovic commented on src/main/groovy/edu/oregonstate/mist/students/db/HttpStudentsDAO.groovy
> +                def term = params?.term
It's good to code defensively here, but it would be unexpected for the backend API to return `term not found` without a term parameter ever given. If this happens, I think an exception should be raised because it's an unexpected behavior that I don't think we should quietly ignore. What are your thoughts?

2018-10-26 15:26 UTC, jaredkosanovic commented on src/main/groovy/edu/oregonstate/mist/students/db/HttpStudentsDAO.groovy
> +            def measures = student[0]["measures"][0]
Would the student list every contain more than 1 item? Would the measures list every contain more than 1 item?

2018-10-26 15:26 UTC, jaredkosanovic commented on swagger.yaml
> +  /students/{osuID}/general:
I'm thinking we should use something different besides "general" because it doesn't really explain what the resource is. Maybe `/classification`?

2018-10-26 15:26 UTC, jaredkosanovic commented on src/main/groovy/edu/oregonstate/mist/students/db/HttpStudentsDAO.groovy
> +            classification = getFieldbyId(studentClassificationsEndpoint, classificationId, "title")
What do you think about getting these two fields in parallel so we don't need to execute them sequentially? The locations API implemented a way of doing this: https://github.com/osu-mist/locations-api/blob/8c10d4920ab055860693e9d05f83fda3cb06dead/src/main/groovy/edu/oregonstate/mist/locations/db/IcalUtil.groovy#L25-L38

2018-10-26 15:40 UTC, tsoliangwu0130 commented on swagger.yaml
> +              firstName:
My main thinking was the /general endpoint should return all basic information about this student. I knew persons API contains the name information, but it doesn't hurt if we also include basic info at /general like name or something. However, if we wanna change the endpoint the /classification, then yeah that totally makes sense not to include these data.

2018-10-26 16:27 UTC, tsoliangwu0130 commented on src/main/groovy/edu/oregonstate/mist/students/db/HttpStudentsDAO.groovy
> +            def measures = student[0]["measures"][0]
For student list, no, since we filter out the result by using personGUID which should is a globally unique identifier for a person and we won't get more than one person.

For measures list, as far as I can see, still no. However, I'm not 100% sure. I also had the same question as you do so I've asked Lance about this question. Let's see if he can give me any suggestion like checking which table in the banner.

2018-10-26 16:28 UTC, tsoliangwu0130 commented on src/main/groovy/edu/oregonstate/mist/students/db/HttpStudentsDAO.groovy
> +            classification = getFieldbyId(studentClassificationsEndpoint, classificationId, "title")
Good idea.

2018-10-30 16:24 UTC, jaredkosanovic requested changes

2018-10-30 16:24 UTC, jaredkosanovic commented on src/main/groovy/edu/oregonstate/mist/students/db/HttpStudentsDAO.groovy
> +                "Term is required for RESTful request"
"Term is required for RESTful request" should not be treated as an invalid term. Our API will return a message saying a the term is invalid if the backend api returns "Term is required for RESTful request", but this means that any term the client gives will result in the same error (even if the term is valid). I think a term not being required should be handled in our code explicitly. For example, if we're wrapping an endpoint that doesn't require a term, we shouldn't provide a term as an acceptable query parameter.

2018-10-30 16:24 UTC, jaredkosanovic commented on swagger.yaml
> +      description: Get a student's genral information
Could you make the description a little more detailed?

2018-10-30 16:24 UTC, jaredkosanovic commented on src/main/groovy/edu/oregonstate/mist/students/StudentsResource.groovy
> +            links: getSelfLink(uriBuilder.genericUri("general", osuID)),
minor comment, don't forget to change "general" in this line

2018-10-30 18:12 UTC, jaredkosanovic approved these changes

2018-10-30 18:26 UTC, merged